config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views import defaults as default_views
from django.views.generic import RedirectView, TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("dashboard:index")), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("walletapp.users.urls", namespace="users")),
    path("incomes/", include("walletapp.incomes.urls", namespace="incomes")),
    path("expenses/", include("walletapp.expenses.urls", namespace="expenses")),
    path("dashboard/", include("walletapp.dashboard.urls", namespace="dashboard")),
    path("credits/", include("walletapp.credits.urls", namespace="credits")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

walletapp/credits/urls.py
from django.urls import path

from .views import CreditCreateView, CreditListView, CreditPayView, CreditUpdateView

app_name = "credits"
urlpatterns = [
    path("", CreditListView.as_view(), name="index"),
    path("create/", CreditCreateView.as_view(), name="create"),
    path("update/<int:pk>/", CreditUpdateView.as_view(), name="update"),
    path("pay/<int:pk>/", CreditPayView.as_view(), name="pay"),
]

walletapp/incomes/urls.py
from django.urls import path

from walletapp.incomes.views import (
    create_income_view,
    delete_incomes_view,
    edit_income_view,
    index_view,
    new_income_view,
    update_income_view,
)

app_name = "incomes"
urlpatterns = [
    path("<int:page_number>/", view=index_view, name="index"),
    path("new/", view=new_income_view, name="new"),
    path("create/", view=create_income_view, name="create"),
    path("edit/<int:pk>/", view=edit_income_view, name="edit"),
    path("update/<int:pk>/", view=update_income_view, name="update"),
    path("delete/<int:pk>/", view=delete_incomes_view, name="delete"),
]

walletapp/users/urls.py
from django.urls import path

from walletapp.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

walletapp/dashboard/models.py
# Create your models here.

walletapp/credits/forms.py
from django import forms

from .choices import CREDIT_ACTIVE, CREDIT_STATUS_CHOICES
from .models import Credit


class CreditForm(forms.ModelForm):
    concept = forms.CharField(label="")
    amount = forms.IntegerField(label="")
    status = forms.ChoiceField(
        label=None,
        choices=CREDIT_STATUS_CHOICES,
        initial=CREDIT_ACTIVE,
        required=False,
        widget=forms.Select(
            attrs={
                "disabled": "true",
                "class": "form-control br-8px",
            },
        ),
    )

    class Meta:
        model = Credit
        fields = [
            "concept",
            "amount",
            "status",
        ]

walletapp/credits/views.py
from datetime import datetime
from typing import Any

from django.contrib import messages
from django.db.models import Sum
from django.db.models.manager import BaseManager
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, ListView, UpdateView

from .forms import CreditForm
from .models import Credit

MAX_ITEMS_PER_PAGE = 10


class CreditListView(ListView):
    model = Credit
    template_name = "credits/index.html"
    paginate_by = MAX_ITEMS_PER_PAGE

    def get_queryset(self) -> BaseManager[Credit]:
        return Credit.objects.filter(status="active")

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        total_amount = (
            queryset.only("amount").aggregate(Sum("amount")).get("amount__sum", 0)
        )
        _, _, queryset, _ = self.paginate_queryset(queryset, MAX_ITEMS_PER_PAGE)
        total_amount_per_page = queryset.only("amount").aggregate(Sum("amount"))
        total_amount_per_page = total_amount_per_page.get("amount__sum", 0)
        context.update(
            title="Credits",
            total_amount_per_page=total_amount_per_page,
            total_amount=total_amount,
        )
        return context


class CreditCreateView(CreateView):
    model = Credit
    template_name = "credits/form.html"
    form_class = CreditForm

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        current_date = datetime.now().strftime("%Y-%m-%d")
        context.update(title="Create credit", current_date=current_date)
        return context

    def get_success_url(self) -> str:
        messages.success(self.request, message="Credit was created successfully!")
        return reverse("credits:index")


class CreditUpdateView(UpdateView):
    model = Credit
    template_name = "credits/form.html"
    queryset = Credit.objects.filter(status="active")
    form_class = CreditForm

    def get_success_url(self) -> str:
        messages.success(self.request, message="Credit was updated successfully!")
        return reverse("credits:index")

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super(UpdateView, self).get_context_data(**kwargs)
        context.update(title="Update credit")
        return context


class CreditPayView(UpdateView):
    model = Credit
    template_name = "credits/pay_credit_form.html"
    queryset = Credit.objects.filter(status="active")
    form_class = CreditForm

    def post(self, request: HttpRequest, pk: int):
        credit = get_object_or_404(Credit, pk=pk)
        payment_value = request.POST.get("payment", 0)

        credit.amount -= int(payment_value)
        credit.save()

        messages.success(request, message="Added payment to credit!")
        return redirect(reverse("credits:index"))

    def get_success_url(self) -> str:
        messages.success(self.request, message="Added payment to credit successfully!")
        return reverse("credits:index")

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super(UpdateView, self).get_context_data(**kwargs)
        context.update(title="Pay credit")
        return context

walletapp/dashboard/views.py
from django.shortcuts import render
from django.views.generic import View

from walletapp.credits.models import Credit
from walletapp.expenses.models import Expense
from walletapp.incomes.models import Income

from .repository import (
    get_flatten_lists,
    get_model_with_kind_property,
    get_total_amount,
)


class DashboardView(View):
    def get(self, request):
        expenses = Expense.objects.all()
        incomes = Income.objects.all()
        credits_ = Credit.objects.filter(status="active")

        total_incomes_amount = get_total_amount(incomes)
        total_expenses_amount = get_total_amount(expenses)
        total_credits_amount = get_total_amount(credits_)
        wallet_amount = (
            total_incomes_amount - total_expenses_amount - total_credits_amount
        )

        expenses = get_model_with_kind_property(expenses, "Expense")
        incomes = get_model_with_kind_property(incomes, "Income")
        credits_ = get_model_with_kind_property(credits_, "Credit")

        obj_list = get_flatten_lists(expenses, incomes, credits_)
        context = {
            "title": "Dashboard",
            "obj_list": obj_list,
            "total_incomes": total_incomes_amount,
            "total_expenses": total_expenses_amount,
            "total_credits": total_credits_amount,
            "wallet_amount": wallet_amount,
        }
        return render(request, template_name="dashboard/index.html", context=context)

walletapp/expenses/views.py
from datetime import datetime
from typing import Any

from django.contrib import messages
from django.db.models import Sum
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import ExpenseForm
from .models import Expense

MAX_ITEMS_PER_PAGE = 10


class ExpenseListView(ListView):
    model = Expense
    template_name = "expenses/index.html"
    paginate_by = MAX_ITEMS_PER_PAGE
    queryset = Expense.objects.all().order_by("-pk")

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        total_amount = (
            queryset.only("amount").aggregate(Sum("amount")).get("amount__sum", 0)
        )
        _, _, queryset, _ = self.paginate_queryset(queryset, MAX_ITEMS_PER_PAGE)
        total_paginated = queryset.only("amount").aggregate(Sum("amount"))
        total_paginated = total_paginated.get("amount__sum", 0)
        context.update(
            title="Expenses", total_paginated=total_paginated, total_amount=total_amount
        )
        return context


class ExpenseCreateView(CreateView):
    model = Expense
    fields = ["concept", "amount"]
    success_url = reverse_lazy("expenses:index", kwargs={"page_number": 1})

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        current_date = datetime.now()
        current_date = current_date.strftime("%Y-%m-%d")
        context.update(title="Create expenses", current_date=current_date)
        return context

    def post(self, request: HttpRequest) -> HttpResponse:
        forms = [
            ExpenseForm(dict(concept=concept, amount=amount))
            for concept, amount in zip(
                request.POST.getlist("concept"), request.POST.getlist("amount")
            )
        ]
        if not all(form.is_valid() for form in forms):
            messages.error(request, message="Form is not valid!")
            return redirect(reverse("expenses:create"))

        for form in forms:
            form.save()

        if len(forms) > 1:
            messages.success(request, message="Expenses were created successfully")
        else:
            messages.success(request, message="Expense was created successfully")
        return redirect(reverse("expenses:index"))


class ExpenseUpdateView(UpdateView):
    model = Expense
    template_name = "expenses/expense_update_form.html"
    success_url = reverse_lazy("expenses:index")
    form_class = ExpenseForm

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(title="Update expense")
        return context

    def get_form(self, form_class=ExpenseForm):
        form = super().get_form(form_class)

        if form.is_valid():
            messages.success(self.request, message="Expense was updated successfully!")
        else:
            messages.error(self.request, message="Form is not valid!")

        return form


class ExpenseDeleteView(DeleteView):
    model = Expense
    template_name = "expenses/confirm_delete.html"

    def get_success_url(self) -> str:
        messages.success(self.request, message="Expense was deleted successfully!")
        return reverse_lazy("expenses:index")

walletapp/incomes/views.py
from datetime import datetime

from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import IncomeForm
from .models import Income

MAX_ITEMS_PER_PAGE = 10


def index_view(request: HttpRequest, page_number: int) -> HttpResponse:
    queryset = Income.objects.all().order_by("-pk")
    paginator = Paginator(queryset, MAX_ITEMS_PER_PAGE)
    page_obj = paginator.page(page_number)
    object_list = page_obj.object_list
    total_amount = (
        queryset.only("amount").aggregate(Sum("amount")).get("amount__sum", 0)
    )
    total_paginated = (
        object_list.only("amount").aggregate(Sum("amount")).get("amount__sum", 0)
    )

    context = {
        "page_obj": page_obj,
        "object_list": object_list,
        "title": "Incomes",
        "total_amount": total_amount,
        "total_paginated": total_paginated,
        "paginator": paginator,
    }
    return render(request, template_name="incomes/index.html", context=context)


def new_income_view(request: HttpRequest) -> HttpRequest:
    current_date = datetime.now()
    current_date = current_date.strftime("%Y-%m-%d")
    context = {
        "title": "Create incomes",
        "current_date": current_date,
    }
    return render(request, template_name="incomes/form.html", context=context)


def create_income_view(request: HttpRequest) -> HttpRequest:
    if not request.method == "POST":
        return redirect(reverse("incomes:new", kwargs={"page_number": 1}))

    forms = [
        IncomeForm(dict(concept=concept, amount=amount))
        for concept, amount in zip(
            request.POST.getlist("concept"),
            request.POST.getlist("amount"),
        )
    ]
    if not all(form.is_valid for form in forms):
        messages.error(request, message="Form is not valid!")
        return redirect(reverse("incomes:new"))

    for form in forms:
        form.save()

    if len(forms) > 1:
        messages.success(request, message="Expenses were created successfully")
    else:
        messages.success(request, message="Expense was created successfully")
    return redirect(reverse("incomes:index", kwargs={"page_number": 1}))


def edit_income_view(request: HttpRequest, pk: int) -> HttpResponse:
    income = get_object_or_404(Income, pk=pk)

    context = {"title": "Update income", "income": income}
    return render(request, template_name="incomes/form.html", context=context)


def update_income_view(request: HttpRequest, pk: int) -> HttpResponse:
    income = get_object_or_404(Income, pk=pk)

    if not request.method == "POST":
        return redirect(reverse("incomes:index", kwargs={"page_number": 1}))

    form = IncomeForm(request.POST, instance=income)

    if not form.is_valid():
        messages.error(request, message="Form is not valid!")
        return redirect(reverse("incomes:edit", kwargs={"pk": pk}))

    form.save()

    messages.success(request, message="Income was updated successfully!")
    return redirect(reverse("incomes:index", kwargs={"page_number": 1}))


def delete_incomes_view(request: HttpRequest, pk: int) -> HttpResponse:
    income = get_object_or_404(Income, pk=pk)

    if request.method == "POST":
        income.delete()
        messages.success(request, message="Income was deleted successfully!")
        return redirect(reverse("incomes:index", kwargs={"page_number": 1}))

    context = {
        "object": income,
    }
    return render(request, template_name="incomes/delete.html", context=context)

walletapp/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

walletapp/templates/incomes/delete.html
{% extends "base.html" %}
{% load crispy_forms_tags static i18n compress %}
{% block title %}{{ title }}{% endblock %}


{% block content %}
    <div class="center h-100vh w-100%">
        {% compress css %}
        <link rel="stylesheet" type="text/x-scss" href="{% static 'scss/new_income.scss' %}" />
        {% endcompress %}
        <form
        method="POST"
        action="{% url 'incomes:delete' object.pk %}"
        class="form-horizontal flex-space-around mt-5 mb-5 bordered bg-white w-60%">
        {% csrf_token %}
        <div class="form-header bg-red mb-4">
            <h1>Delete {{ object.concept }}?</h1>
        </div>
        <div class="form-body">
            <div class="mb-3 center h-100%">
                <div class="column">
                    <h4>Are you sure do you want to delete
                        <span class="italic grey-light">{{ object.concept }}</span>
                        income?
                    </h4>

                    <div class="row1 center mt-4">
                        <a href="{% url 'incomes:index' 1 %}" class="btn btn-danger">Cancel</a>
                        <div class="w-20px"></div>
                        <button class="btn btn-primary">Delete</button>
                    </div>
                </div>
            </div>
        </div>
        </form>
    </div>
{% endblock %}

walletapp/templates/incomes/form.html
{% extends "base.html" %}
{% load crispy_forms_tags static i18n compress %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
  {% compress css %}
  <link rel="stylesheet" type="text/x-scss" href="{% static 'scss/new_income.scss' %}" />
  {% endcompress %}
  {% compress js %}
  <script defer src="{% static 'js/new_income.js' %}"></script>
  {% endcompress %}
<div class="center w-100% h-100vh">
  <form
  class="form-horizontal flex-space-around mt-5 mb-5 bordered bg-white {% if title == 'Update income' %} h-40vh {% else %} h-80 {% endif %}"
  method="POST"
  {% if title == 'Create incomes' %}
  action="{% url 'incomes:create' %}"
  {% else %}
  action="{% url 'incomes:update' income.pk %}"
  {% endif %}>
    <div class="form-header mb-4">
      <h1>{{ title}}</h1>
    </div>
    {% csrf_token %}
    <div class="form-body">
      <div class="mb-3 w-80%">
        <div id="inputs">
          <div class="input-group">
            {% if income %}
            <span class="input-group-text br-8px"><i class="fa-solid fa-list"></i></i></span>
            <input type="text" name="concept" class="form-control br-8px" placeholder="Concept" value="{{ income.concept }}" required>
            <span class="input-group-text">$</span>
            <input type="number" name="amount" class="form-control br-8px" placeholder="0.00" min="100" value="{{ income.amount }}" step="0.25" pattern="^\d*(\.\d{0,2})?$" required>
            <span class="input-group-text br-8px"><i class="fa-regular fa-calendar"></i></span>
            <input type="date" name="created_at" class="form-control br-8px" value="{{ income.get_created_at }}" readonly>
            {% else %}
            <span class="input-group-text br-8px"><i class="fa-solid fa-list"></i></span>
            <input type="text" name="concept" class="form-control br-8px" placeholder="Concept" required>
            <span class="input-group-text">$</span>
            <input type="number" name="amount" class="form-control br-8px" placeholder="0.00" min="100" step="0.25" pattern="^\d*(\.\d{0,2})?$" required>
            <span class="input-group-text br-8px"><i class="fa-regular fa-calendar"></i></span>
            <input type="date" name="created_at" class="form-control br-8px" value="{{ current_date }}" readonly>
            {% endif %}
          </div>
        </div>
        {% if title == 'Create incomes' %}
        <div class="input-control mb-3 mt-4">
          <span id="add_other_income" class="ml-4 btn btn-light"><i class="fa-solid fa-plus"></i></</span>
        </div>
        {% endif %}
      </div>

      <div class="input-control mb-3 w-80% flex justify-end">
        <a class="btn btn-danger" href="{% url 'incomes:index' 1 %}">Cancel</a>
        <span class="w-20px"></span>
        <button type="submit" class="btn btn-primary">
          {% if title == 'Create incomes' %}
            Create
          {% else %}
            Update
          {% endif %}
        </button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

walletapp/templates/incomes/index.html
{% extends "base.html" %}
{% load crispy_forms_tags static i18n compress money %}
{% block title %}{{ title }}{% endblock %}


{% block content %}
<div class="table-container mt-5 mb-5">
    <div class="table-header bg-violet">
        <div class="flex">total:&nbsp;<h5>{{ total_amount|money }}</h5></div>
        <h1>{{ title }}</h1>
        <a href="{% url 'incomes:new' %}" class="btn btn-primary">Add income</a>
    </div>
    <table class="table">
        <thead>
            <tr class="bg-light table-striped">
            <th scope="col">id</th>
            <th scope="col">Concept</th>
            <th scope="col">Amount</th>
            <th scope="col">Created at</th>
            <th scope="col">Updated at</th>
            <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for income in object_list %}
            <tr>
            <th scope="row">{{ income.id }}</th>
            <td>{{ income.concept }}</td>
            <td>{{ income.amount|money }}</td>
            <td>{{ income.get_full_created_at }}</td>
            <td>{{ income.get_full_updated_at }}</td>
            <td>
                <div class="table-actions">
                    <a class="btn btn-primary" href="{% url 'incomes:edit' income.id %}">Update</a>
                    <a class="btn btn-danger" href="{% url 'incomes:delete' income.id %}">Delete</a>
                </div>
            </td>
            </tr>
            {% endfor %}
            <tr>
                <th scope="row">Total</td>
                <th></th>
                <th scope="row">{{ total_paginated|money }}</td>
                <th></th>
                <th></th>
            </tr>
        </tbody>
    </table>
    <div class="table-footer w-100%">
        <div class="table-paginator">
            <div>
                <p class="lead pt-3">page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</p>
            </div>
            <div>
                {% if page_obj.has_previous %}
                    <a href="{% url 'incomes:index' page_obj.previous_page_number %}" class="btn btn-light"><</a>
                {% else %}
                    <a class="btn btn-light"><</a>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                        <a class="btn btn-primary">{{ i }}</a>
                        {% else %}
                        <a href="{% url 'incomes:index' i %}" class="btn btn-light">{{ i }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <a href="{% url 'incomes:index' page_obj.next_page_number %}" class="btn btn-light">></a>
                    {% else %}
                        <a class="btn btn-light">></a>
                    {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}